import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../component/Navbar'
import Sidenav from '../component/Sidenav'
import CreatePost from '../component/CreatePost'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidenav />
      <div className=" mx-auto absolute top-20 left-1/2 transform -translate-x-1/2 flex justify-center lg:w-7/12 w-10/12">
        <CreatePost />
      </div>
    </div>
  )
}
